const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const ago=t=>{const d=t?.toDate?t.toDate():t?new Date(t):new Date();let x=Math.floor((Date.now()-d)/1000);if(x<60)return `${x}s`;x=Math.floor(x/60);if(x<60)return `${x}m`;x=Math.floor(x/60);if(x<24)return `${x}h`;x=Math.floor(x/24);if(x<30)return `${x}d`;return d.toLocaleDateString()};
const avatar=u=>u?.photoURL?`<img src="${esc(u.photoURL)}" alt="">`:esc((u?.displayName||u?.username||"?").slice(0,1).toUpperCase());
const linkify=s=>esc(s).replace(/(^|\s)(#[a-zA-Z0-9_]+)/g,'$1<a href="#/explore?q=$2">$2</a>').replace(/(^|\s)(@[a-zA-Z0-9_]+)/g,'$1<a href="#/profile/$2">$2</a>');

let fb,auth,db,api={};
let state={user:null,profile:null,route:"home",posts:[],following:new Set(),blocked:new Set(),muted:new Set(),notifications:[],conversations:[],bookmarks:new Set(),settings:{},loading:false};

async function init(){
  api=await fetch("/api/config").then(r=>r.json());
  if(!api.firebase?.apiKey) throw Error("Firebase client configuration is missing. Add FIREBASE_* environment variables to Render.");
  fb=await import("https://www.gstatic.com/firebasejs/12.4.0/firebase-app.js");
  const A=await import("https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js");
  const F=await import("https://www.gstatic.com/firebasejs/12.4.0/firebase-firestore.js");
  const app=fb.initializeApp(api.firebase);auth=A.getAuth(app);db=F.getFirestore(app);Object.assign(window,{A,F});
  A.onAuthStateChanged(auth,async u=>{state.user=u;if(u){await hydrateUser();await loadSocial();}render();});
  window.addEventListener("hashchange",()=>{parseRoute();render();});
  parseRoute();render();
}
function parseRoute(){let h=location.hash.replace(/^#\/?/,"");let [path,q]=h.split("?");let parts=path.split("/").filter(Boolean);state.route=parts[0]||"home";state.routeId=parts.slice(1).join("/");state.query=new URLSearchParams(q||"");}
const C=()=>window.F;
async function hydrateUser(){const s=await C().getDoc(C().doc(db,"users",state.user.uid));if(s.exists())state.profile={id:s.id,...s.data()};else{state.profile={id:state.user.uid,username:(state.user.email||"user").split("@")[0].replace(/[^a-z0-9_]/gi,""),displayName:state.user.displayName||"New User",bio:"",photoURL:state.user.photoURL||"",settings:{}};await C().setDoc(C().doc(db,"users",state.user.uid),state.profile,{merge:true})}state.settings=state.profile.settings||{};applyAppearance()}
async function loadSocial(){try{const F=C();let f=await F.getDocs(F.query(F.collection(db,"follows"),F.where("followerId","==",state.user.uid)));state.following=new Set(f.docs.map(x=>x.data().followingId));let b=await F.getDocs(F.query(F.collection(db,"blocks"),F.where("blockerId","==",state.user.uid)));state.blocked=new Set(b.docs.map(x=>x.data().blockedId));let m=await F.getDocs(F.query(F.collection(db,"mutes"),F.where("muterId","==",state.user.uid)));state.muted=new Set(m.docs.map(x=>x.data().mutedId));let n=await F.getDocs(F.query(F.collection(db,"notifications"),F.where("recipientId","==",state.user.uid),F.orderBy("createdAt","desc"),F.limit(50)));state.notifications=n.docs.map(d=>({id:d.id,...d.data()}));let bm=await F.getDocs(F.query(F.collection(db,"bookmarks"),F.where("userId","==",state.user.uid)));state.bookmarks=new Set(bm.docs.map(x=>x.data().postId));}catch(e){console.warn("Social data partially unavailable",e)} }
async function loadPosts(){state.loading=true;render();try{const F=C();const s=await F.getDocs(F.query(F.collection(db,"posts"),F.orderBy("createdAt","desc"),F.limit(100)));let arr=s.docs.map(d=>({id:d.id,...d.data()})).filter(p=>!state.blocked.has(p.authorId)&&!state.muted.has(p.authorId)&&!p.hidden);for(const p of arr){let [ls,cs,rs]=await Promise.all([F.getDocs(F.query(F.collection(db,"likes"),F.where("postId","==",p.id))),F.getDocs(F.query(F.collection(db,"comments"),F.where("postId","==",p.id))),F.getDocs(F.query(F.collection(db,"reposts"),F.where("postId","==",p.id)))]);p.likeCount=ls.size;p.commentCount=cs.size;p.repostCount=rs.size;p.liked=ls.docs.some(x=>x.data().userId===state.user.uid);p.bookmarked=state.bookmarks.has(p.id)}state.posts=arr;}catch(e){toast(`Could not load the feed: ${e.message}`)}finally{state.loading=false;render()}}
async function saveSettings(patch){state.settings={...state.settings,...patch};await C().setDoc(C().doc(db,"users",state.user.uid),{settings:state.settings},{merge:true});applyAppearance();toast("Settings saved")}
function applyAppearance(){document.body.classList.toggle("dark",state.settings.theme==="dark"||(state.settings.theme==="system"&&matchMedia("(prefers-color-scheme:dark)").matches));document.body.classList.toggle("compact",!!state.settings.compact);document.body.classList.toggle("reduce-motion",!!state.settings.reduceMotion)}
function toast(msg){const old=$(".toast");if(old)old.remove();const x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.append(x);setTimeout(()=>x.remove(),3000)}
function shell(main){const unread=state.notifications.filter(n=>!n.read).length;return `<div class="shell"><header class="topbar"><a class="logo" href="#/home">Simple Social</a><div class="search"><input id="globalSearch" placeholder="Search people, posts, #hashtags…" value="${esc(state.query?.get("q")||"")}"></div><button class="btn primary desktop-only" data-action="compose">Post</button></header><div class="layout"><aside class="side"><nav class="nav">${nav("home","⌂","Home")}${nav("explore","⌕","Explore")}${nav("messages","✉","Messages")}${nav("notifications","♡",`Notifications${unread?` (${unread})`:``}`)}${nav("bookmarks","▱","Bookmarks")}${nav("profile","◎","Profile")}${nav("analytics","◫","Analytics")}${nav("settings","⚙","Settings")}<button data-action="signout" class="danger">↪ <span>Sign out</span></button></nav></aside><main>${main}</main><aside class="rightcol">${rightbar()}</aside></div><nav class="mobile-nav">${nav("home","⌂","")}${nav("explore","⌕","")}${nav("messages","✉","")}${nav("notifications","♡","")}${nav("profile","◎","")}</nav></div>`}
function nav(route,icon,label){return `<button class="${state.route===route?"active":""}" data-nav="${route}">${icon} <span>${label}</span></button>`}
function rightbar(){return `<div class="card" style="padding:16px"><div class="right-title">Trending</div><div id="trends"><div class="muted">Loading trends…</div></div></div><div class="card" style="padding:16px;margin-top:14px"><div class="right-title">Your account</div><div class="row"><div class="avatar">${avatar(state.profile)}</div><div><b>${esc(state.profile?.displayName)}</b><div class="handle">@${esc(state.profile?.username)}</div></div></div></div>`}
async function page(){switch(state.route){case"home":return home();case"explore":return await explore();case"profile":return await profile(state.routeId);case"messages":return await messages();case"notifications":return notifications();case"bookmarks":return bookmarks();case"analytics":return await analytics();case"settings":return settings();default:return `<div class="card empty">Page not found. <a href="#/home">Go home</a></div>`}}
function home(){return `<h1 class="page-title">Home</h1>${composer()}<div id="feed">${state.loading?loading():state.posts.length?state.posts.map(postCard).join(""):`<div class="card empty">No posts yet. Follow someone or make the first post.</div>`}</div>`}
function loading(){return `<div class="card empty"><div class="spinner" style="margin:auto"></div><p>Loading your feed…</p></div>`}
function composer(){return `<div class="card composer"><div class="row"><div class="avatar">${avatar(state.profile)}</div><textarea id="composerText" placeholder="What's happening, ${esc(state.profile?.displayName||"there")}?"></textarea></div><div class="actions"><input id="mediaInput" type="file" accept="image/*,video/*" multiple hidden><button class="btn" data-action="media">＋ Media</button><button class="btn" data-action="poll">Poll</button><button class="btn" data-action="draft">Save draft</button><span class="grow"></span><button class="btn primary" data-action="post">Post</button></div><div id="composerExtras"></div></div>`}
function postCard(p){return `<article class="card post" data-post="${p.id}"><div class="post-head"><a href="#/profile/${encodeURIComponent(p.authorUsername||p.authorId)}" class="avatar">${avatar({displayName:p.authorName,photoURL:p.authorPhotoURL})}</a><div class="grow"><div><b class="name">${esc(p.authorName||"User")}</b> <span class="handle">@${esc(p.authorUsername||"")}</span></div><div class="time">${ago(p.createdAt)}${p.editedAt?" · edited":""}</div></div><button class="iconbtn" data-menu="${p.id}">•••</button></div><div class="post-text">${linkify(p.text||"")}</div>${mediaHTML(p.media)}${p.poll?pollHTML(p):""}<div class="post-actions"><button class="iconbtn ${p.liked?"active":""}" data-like="${p.id}">♥ ${p.likeCount||0}</button><button class="iconbtn" data-comments="${p.id}">💬 ${p.commentCount||0}</button><button class="iconbtn" data-repost="${p.id}">↻ ${p.repostCount||0}</button><button class="iconbtn ${p.bookmarked?"active":""}" data-bookmark="${p.id}">🔖</button><button class="iconbtn" data-share="${p.id}">↗</button></div><div id="comments-${p.id}"></div></article>`}
function mediaHTML(m){if(!Array.isArray(m)||!m.length)return"";return `<div class="media-grid">${m.map(x=>x.type==="video"?`<video src="${esc(x.url)}" controls preload="metadata"></video>`:`<img src="${esc(x.url)}" alt="${esc(x.alt||"")}" loading="lazy">`).join("")}</div>`}
function pollHTML(p){let opts=p.poll.options||[],total=opts.reduce((a,o)=>a+(o.votes||0),0);return `<div class="poll">${opts.map((o,i)=>{let pct=total?Math.round((o.votes||0)/total*100):0;return `<button class="poll-option" data-vote="${p.id}:${i}"><div class="bar" style="width:${pct}%"></div><span>${esc(o.text)} <b>${pct}%</b></span></button>`}).join("")}<small class="muted">${total} vote${total===1?"":"s"}</small></div>`}
async function createPost(){const text=$("#composerText")?.value.trim();const extras=$("#composerExtras");let poll=null;if(extras?.dataset.poll){const options=extras.dataset.poll.split("||").filter(Boolean).map(text=>({text,votes:0}));if(options.length>=2)poll={options}}const files=[...($("#mediaInput")?.files||[])];if(!text&&!files.length&&!poll)return toast("Write something first.");try{let media=[];if(files.length){const token=await state.user.getIdToken();const fd=new FormData();files.forEach(f=>fd.append("files",f));const r=await fetch("/api/media/upload",{method:"POST",headers:{Authorization:`Bearer ${token}`},body:fd});const j=await r.json();if(!r.ok)throw Error(j.error||"Upload failed");media=j.media}await C().addDoc(C().collection(db,"posts"),{authorId:state.user.uid,authorName:state.profile.displayName||state.profile.username,authorUsername:state.profile.username,authorPhotoURL:state.profile.photoURL||"",text,media,poll,createdAt:C().serverTimestamp(),visibility:"public",editedAt:null});$("#composerText").value="";if(extras){extras.innerHTML="";delete extras.dataset.poll}toast("Posted!");await loadPosts()}catch(e){toast(e.message)}}
async function toggleLike(id){const F=C(),ref=F.doc(db,"likes",`${id}_${state.user.uid}`);const s=await F.getDoc(ref);if(s.exists())await F.deleteDoc(ref);else await F.setDoc(ref,{postId:id,userId:state.user.uid,createdAt:F.serverTimestamp()});const p=state.posts.find(x=>x.id===id);if(p){p.liked=!s.exists();p.likeCount=Math.max(0,(p.likeCount||0)+(s.exists()?-1:1));render()}if(!s.exists()){const p=state.posts.find(x=>x.id===id);if(p)notify(p.authorId,"like",id)}}
async function toggleBookmark(id){const F=C(),ref=F.doc(db,"bookmarks",`${state.user.uid}_${id}`),s=await F.getDoc(ref);if(s.exists()){await F.deleteDoc(ref);state.bookmarks.delete(id)}else{await F.setDoc(ref,{userId:state.user.uid,postId:id,createdAt:F.serverTimestamp()});state.bookmarks.add(id)}const p=state.posts.find(x=>x.id===id);if(p)p.bookmarked=!s.exists();render()}
async function addComment(id,text){const clean=text.trim();if(!clean)return;await C().addDoc(C().collection(db,"comments"),{postId:id,authorId:state.user.uid,authorName:state.profile.displayName||state.profile.username,authorUsername:state.profile.username,text:clean,createdAt:C().serverTimestamp()});const p=state.posts.find(x=>x.id===id);if(p)p.commentCount=(p.commentCount||0)+1;try{if(p)await notify(p.authorId,"comment",id)}catch{}render()}
async function loadComments(id){const F=C();const s=await F.getDocs(F.query(F.collection(db,"comments"),F.where("postId","==",id),F.orderBy("createdAt","asc")));const box=$(`#comments-${CSS.escape(id)}`);if(!box)return;box.innerHTML=`<div class="comments">${s.docs.map(d=>{const x=d.data();return `<div class="comment"><div class="avatar">${avatar({displayName:x.authorName})}</div><div class="comment-body"><b>${esc(x.authorName)}</b><div>${linkify(x.text)}</div><small class="muted">${ago(x.createdAt)}</small></div></div>`}).join("")}<form class="comment-form" data-comment-form="${id}"><input name="text" placeholder="Write a reply…"><button class="btn primary">Send</button></form></div>`}
async function repost(id){const F=C(),ref=F.doc(db,"reposts",`${state.user.uid}_${id}`),s=await F.getDoc(ref);if(s.exists())return toast("You already reposted this.");const p=state.posts.find(x=>x.id===id);await F.setDoc(ref,{userId:state.user.uid,postId:id,authorId:p?.authorId||"",createdAt:F.serverTimestamp()});if(p)p.repostCount=(p.repostCount||0)+1;toast("Reposted");render()}
async function notify(recipientId,type,postId=""){if(!recipientId||recipientId===state.user.uid)return;const prefs=state.settings||{};if(type==="like"&&prefs.notifyLikes===false)return;if(type==="comment"&&prefs.notifyComments===false)return;await C().addDoc(C().collection(db,"notifications"),{recipientId,type,actorId:state.user.uid,actorName:state.profile.displayName||state.profile.username,postId,read:false,createdAt:C().serverTimestamp()})}
async function searchUsers(q){const F=C();const s=await F.getDocs(F.query(F.collection(db,"users"),F.orderBy("username"),F.limit(100)));return s.docs.map(d=>({id:d.id,...d.data()})).filter(u=>(u.username||"").toLowerCase().includes(q.toLowerCase())||(u.displayName||"").toLowerCase().includes(q.toLowerCase())).slice(0,20)}
async function explore(){const q=state.query?.get("q")||"";if(q){const users=await searchUsers(q.replace(/^@/,""));return `<h1 class="page-title">Search</h1><div class="card" style="padding:8px;margin-bottom:14px"><div class="list">${users.map(userRow).join("")||`<div class="empty">No people found.</div>`}</div></div>${state.posts.filter(p=>(p.text||"").toLowerCase().includes(q.toLowerCase())||(p.authorUsername||"").toLowerCase().includes(q.toLowerCase())).map(postCard).join("")}`}return `<h1 class="page-title">Explore</h1><div class="card" style="padding:16px;margin-bottom:16px"><h3>Find people</h3><p class="muted">Search users, hashtags, and posts from the bar above.</p></div><div id="explorePosts">${state.posts.map(postCard).join("")||`<div class="card empty">Nothing to explore yet.</div>`}</div>`}
function userRow(u){return `<div class="user-row"><a class="avatar" href="#/profile/${encodeURIComponent(u.username||u.id)}">${avatar(u)}</a><div class="grow"><a href="#/profile/${encodeURIComponent(u.username||u.id)}"><b>${esc(u.displayName||u.username)}</b></a><div class="handle">@${esc(u.username)}</div></div>${u.id!==state.user.uid?`<button class="btn" data-follow="${u.id}">${state.following.has(u.id)?"Following":"Follow"}</button>`:""}</div>`}
async function profile(id){let u;if(!id||id===state.user.uid||id==="me")u=state.profile;else{const F=C();let s=await F.getDoc(F.doc(db,"users",id));if(!s.exists()){const q=await F.getDocs(F.query(F.collection(db,"users"),F.where("username","==",decodeURIComponent(id)),F.limit(1)));if(!q.empty)s=q.docs[0]}u=s?.exists?{id:s.id,...s.data()}:null}if(!u)return `<div class="card empty">User not found.</div>`;const posts=state.posts.filter(p=>p.authorId===u.id);const isFollowing=state.following.has(u.id);return `<div class="card"><div class="profile-cover"></div><div class="profile-body"><div class="avatar profile-avatar">${avatar(u)}</div><div class="row" style="margin-top:10px"><div class="grow"><h1 style="margin:0">${esc(u.displayName||u.username)}</h1><div class="handle">@${esc(u.username)}</div></div>${u.id!==state.user.uid?`<button class="btn primary" data-follow="${u.id}">${isFollowing?"Unfollow":"Follow"}</button><button class="btn" data-message-user="${u.id}">Message</button>`:`<a class="btn" href="#/settings">Edit profile</a>`}</div><p>${linkify(u.bio||"")}</p><div class="muted">${posts.length} posts · joined ${u.createdAt?.toDate?u.createdAt.toDate().toLocaleDateString():"recently"}</div><div class="tabs"><button class="active">Posts</button><button>Replies</button><button>Media</button><button>Likes</button></div></div></div><div style="margin-top:14px">${posts.map(postCard).join("")||`<div class="card empty">No posts yet.</div>`}</div>`}
async function follow(id){const F=C(),ref=F.doc(db,"follows",`${state.user.uid}_${id}`),s=await F.getDoc(ref);if(s.exists()){await F.deleteDoc(ref);state.following.delete(id)}else{await F.setDoc(ref,{followerId:state.user.uid,followingId:id,createdAt:F.serverTimestamp()});state.following.add(id);try{await C().addDoc(C().collection(db,"notifications"),{recipientId:id,type:"follow",actorId:state.user.uid,actorName:state.profile.displayName||state.profile.username,read:false,createdAt:F.serverTimestamp()})}catch{}}render()}
async function messages(){if(!state.conversations.length){try{const F=C();const s=await F.getDocs(F.query(F.collection(db,"conversations"),F.where("members","array-contains",state.user.uid),F.orderBy("updatedAt","desc"),F.limit(50)));state.conversations=s.docs.map(d=>({id:d.id,...d.data()}))}catch(e){return `<h1 class="page-title">Messages</h1><div class="card notice">Could not load messages: ${esc(e.message)}</div>`}}return `<h1 class="page-title">Messages</h1><div class="card list">${state.conversations.map(c=>`<button class="user-row" data-conversation="${c.id}"><div class="avatar">✉</div><div class="grow" style="text-align:left"><b>${esc((c.memberNames||[]).filter((_,i)=>c.members[i]!==state.user.uid).join(", ")||"Conversation")}</b><div class="muted">${esc(c.lastMessage||"No messages yet")}</div></div></button>`).join("")||`<div class="empty">No conversations yet. Open a profile and press Message.</div>`}</div>`}
async function openConversation(otherId){const F=C();let q=await F.getDocs(F.query(F.collection(db,"conversations"),F.where("members","array-contains",state.user.uid)));let c=q.docs.find(d=>d.data().members.includes(otherId));if(!c){const other=await F.getDoc(F.doc(db,"users",otherId));const o=other.data()||{};c=await F.addDoc(F.collection(db,"conversations"),{members:[state.user.uid,otherId],memberNames:[state.profile.displayName||state.profile.username,o.displayName||o.username],createdAt:F.serverTimestamp(),updatedAt:F.serverTimestamp(),lastMessage:""})}location.hash=`#/messages/${c.id}`}
async function conversation(id){const F=C();const cs=await F.getDoc(F.doc(db,"conversations",id));if(!cs.exists())return `<div class="card empty">Conversation not found.</div>`;const c=cs.data();const s=await F.getDocs(F.query(F.collection(db,"messages"),F.where("conversationId","==",id),F.orderBy("createdAt","asc"),F.limit(200)));return `<h1 class="page-title">${esc((c.memberNames||[]).filter((_,i)=>c.members[i]!==state.user.uid).join(", ")||"Conversation")}</h1><div class="card" style="padding:16px"><div id="messageList" style="display:grid;gap:8px;max-height:55vh;overflow:auto">${s.docs.map(d=>{const x=d.data();return `<div style="max-width:75%;padding:10px 12px;border-radius:14px;background:${x.senderId===state.user.uid?'#635bff;color:#fff;margin-left:auto':'var(--surface2)'}"><div>${linkify(x.text)}</div><small style="opacity:.7">${ago(x.createdAt)}</small></div>`}).join("")}</div><form id="messageForm" data-conversation="${id}" class="comment-form" style="margin-top:14px"><input name="text" placeholder="Write a message…" autocomplete="off"><button class="btn primary">Send</button></form></div>`}
function notifications(){return `<h1 class="page-title">Notifications</h1><div class="actions" style="margin-bottom:12px"><button class="btn" data-action="readall">Mark all read</button></div><div class="card list">${state.notifications.map(n=>`<button class="user-row" data-notification="${n.id}"><div class="avatar">${n.type==='like'?'♥':n.type==='comment'?'💬':n.type==='follow'?'＋':'↻'}</div><div class="grow" style="text-align:left"><b>${esc(n.actorName||"Someone")}</b> ${n.type==='like'?'liked your post':n.type==='comment'?'commented on your post':n.type==='follow'?'followed you':'interacted with your post'}<div class="muted">${ago(n.createdAt)}</div></div>${n.read?'':'<b>●</b>'}</button>`).join("")||`<div class="empty">You're all caught up.</div>`}</div>`}
function bookmarks(){const arr=state.posts.filter(p=>state.bookmarks.has(p.id));return `<h1 class="page-title">Bookmarks</h1>${arr.map(postCard).join("")||`<div class="card empty">No saved posts yet.</div>`}`}
async function analytics(){const mine=state.posts.filter(p=>p.authorId===state.user.uid);const totals=mine.reduce((a,p)=>{a.likes+=p.likeCount||0;a.comments+=p.commentCount||0;a.reposts+=p.repostCount||0;return a},{likes:0,comments:0,reposts:0});return `<h1 class="page-title">Analytics</h1><div class="card" style="padding:18px"><div class="row"><div class="grow"><h2>${mine.length}</h2><span class="muted">Posts in loaded window</span></div><div><h2>${totals.likes}</h2><span class="muted">Likes</span></div><div><h2>${totals.comments}</h2><span class="muted">Comments</span></div><div><h2>${totals.reposts}</h2><span class="muted">Reposts</span></div></div></div>`}
function settings(){return `<h1 class="page-title">Settings</h1><div class="card" style="padding:20px"><div class="settings-grid"><div class="setting-nav"><button class="active">General</button><button>Appearance</button><button>Notifications</button><button>Privacy</button></div><section><h2>Profile</h2><div class="field"><label>Display name</label><input id="setName" value="${esc(state.profile.displayName||"")}"></div><div class="field"><label>Username</label><input id="setUsername" value="${esc(state.profile.username||"")}"></div><div class="field"><label>Bio</label><textarea id="setBio">${esc(state.profile.bio||"")}</textarea></div><button class="btn primary" data-action="saveprofile">Save profile</button><h2 style="margin-top:28px">Appearance</h2><div class="field"><label>Theme</label><select id="theme"><option value="system" ${state.settings.theme==='system'?'selected':''}>System</option><option value="light" ${state.settings.theme==='light'?'selected':''}>Light</option><option value="dark" ${state.settings.theme==='dark'?'selected':''}>Dark</option></select></div><label class="toggle">Compact layout <input id="compact" type="checkbox" ${state.settings.compact?'checked':''}></label><label class="toggle">Reduce motion <input id="reduceMotion" type="checkbox" ${state.settings.reduceMotion?'checked':''}></label><h2 style="margin-top:28px">Notifications</h2><label class="toggle">Likes <input id="notifyLikes" type="checkbox" ${state.settings.notifyLikes!==false?'checked':''}></label><label class="toggle">Comments <input id="notifyComments" type="checkbox" ${state.settings.notifyComments!==false?'checked':''}></label><label class="toggle">Follows <input id="notifyFollows" type="checkbox" ${state.settings.notifyFollows!==false?'checked':''}></label><h2 style="margin-top:28px">Privacy</h2><label class="toggle">Private account <input id="privateAccount" type="checkbox" ${state.settings.privateAccount?'checked':''}></label><label class="toggle">Show activity status <input id="activityStatus" type="checkbox" ${state.settings.activityStatus!==false?'checked':''}></label><div class="actions" style="margin-top:18px"><button class="btn primary" data-action="savesettings">Save settings</button></div></section></div></div>`}
async function render(){if(!$("#app"))return;if(!state.user){$("#app").innerHTML=authPage();bind();return}const main=state.route.startsWith("messages/")?"":await page();$("#app").innerHTML=shell(main);if(state.route.startsWith("messages/")&&state.routeId){const x=await conversation(state.routeId);$("main").innerHTML=x}bind();if(state.route==="home"&&!state.posts.length&&!state.loading)loadPosts();if(state.route==="explore"&&!state.posts.length&&!state.loading)loadPosts()}
function authPage(){return `<div class="auth-wrap"><div class="auth-card card"><h1>Simple Social</h1><p class="muted">A vanilla HTML/CSS/JS social network.</p><form id="authForm"><div class="field"><label>Email</label><input name="email" type="email" required></div><div class="field"><label>Password</label><input name="password" type="password" minlength="6" required></div><div class="actions"><button class="btn primary" name="mode" value="login">Sign in</button><button class="btn" name="mode" value="signup">Create account</button></div><div id="authError"></div></form></div></div>`}
function bind(){
  $$('[data-nav]').forEach(b=>b.onclick=()=>{location.hash=`#/${b.dataset.nav}`});
  const search=$("#globalSearch");if(search)search.onkeydown=e=>{if(e.key==='Enter'){const q=search.value.trim();location.hash=`#/explore${q?`?q=${encodeURIComponent(q)}`:""}`}};
  const authForm=$("#authForm");if(authForm)authForm.onsubmit=async e=>{e.preventDefault();const fd=new FormData(authForm);try{if(fd.get("mode")==="signup"){const x=await window.A.createUserWithEmailAndPassword(auth,fd.get("email"),fd.get("password"));await window.A.updateProfile(x.user,{displayName:fd.get("email").split("@")[0]});}else await window.A.signInWithEmailAndPassword(auth,fd.get("email"),fd.get("password"))}catch(err){$("#authError").innerHTML=`<div class="notice">${esc(err.message)}</div>`}};
  $$('[data-action="signout"]').forEach(x=>x.onclick=()=>window.A.signOut(auth));
  $$('[data-action="post"]').forEach(x=>x.onclick=createPost);$$('[data-action="media"]').forEach(x=>x.onclick=()=>$("#mediaInput").click());const mi=$("#mediaInput");if(mi)mi.onchange=()=>toast(`${mi.files.length} file${mi.files.length===1?'':'s'} selected`);
  $$('[data-action="poll"]').forEach(x=>x.onclick=()=>{const ex=$("#composerExtras");ex.innerHTML=`<div class="field"><label>Poll options separated by |</label><input id="pollOptions" placeholder="Option A | Option B | Option C"></div>`;$("#pollOptions").oninput=e=>ex.dataset.poll=e.target.value});
  $$('[data-action="draft"]').forEach(x=>x.onclick=async()=>{const text=$("#composerText")?.value.trim();if(!text)return toast("Nothing to save.");await C().addDoc(C().collection(db,"drafts"),{userId:state.user.uid,text,createdAt:C().serverTimestamp()});toast("Draft saved")});
  $$('[data-like]').forEach(x=>x.onclick=()=>toggleLike(x.dataset.like));$$('[data-bookmark]').forEach(x=>x.onclick=()=>toggleBookmark(x.dataset.bookmark));$$('[data-repost]').forEach(x=>x.onclick=()=>repost(x.dataset.repost));
  $$('[data-comments]').forEach(x=>x.onclick=()=>loadComments(x.dataset.comments));$$('[data-share]').forEach(x=>x.onclick=async()=>{await navigator.clipboard?.writeText(location.origin+location.pathname+`#/post/${x.dataset.share}`);toast("Post link copied")});
  $$('[data-follow]').forEach(x=>x.onclick=()=>follow(x.dataset.follow));$$('[data-message-user]').forEach(x=>x.onclick=()=>openConversation(x.dataset.messageUser));
  $$('[data-comment-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const t=f.elements.text.value;await addComment(f.dataset.commentForm,t);f.elements.text.value="";await loadComments(f.dataset.commentForm)});
  const mf=$("#messageForm");if(mf)mf.onsubmit=async e=>{e.preventDefault();const text=mf.elements.text.value.trim();if(!text)return;await C().addDoc(C().collection(db,"messages"),{conversationId:mf.dataset.conversation,senderId:state.user.uid,text,createdAt:C().serverTimestamp(),read:false});await C().updateDoc(C().doc(db,"conversations",mf.dataset.conversation),{lastMessage:text,updatedAt:C().serverTimestamp()});mf.elements.text.value="";location.hash=`#/messages/${mf.dataset.conversation}`};
  $$('[data-action="readall"]').forEach(x=>x.onclick=async()=>{const F=C();await Promise.all(state.notifications.filter(n=>!n.read).map(n=>F.updateDoc(F.doc(db,"notifications",n.id),{read:true})));state.notifications.forEach(n=>n.read=true);render()});
  const saveP=$('[data-action="saveprofile"]');if(saveP)saveP.onclick=async()=>{const patch={displayName:$("#setName").value.trim(),username:$("#setUsername").value.trim().toLowerCase().replace(/[^a-z0-9_]/g,""),bio:$("#setBio").value};await C().setDoc(C().doc(db,"users",state.user.uid),patch,{merge:true});state.profile={...state.profile,...patch};await window.A.updateProfile(state.user,{displayName:patch.displayName});toast("Profile saved");render()};
  const ss=$('[data-action="savesettings"]');if(ss)ss.onclick=()=>saveSettings({theme:$("#theme").value,compact:$("#compact").checked,reduceMotion:$("#reduceMotion").checked,notifyLikes:$("#notifyLikes").checked,notifyComments:$("#notifyComments").checked,notifyFollows:$("#notifyFollows").checked,privateAccount:$("#privateAccount").checked,activityStatus:$("#activityStatus").checked});
}
init().catch(e=>{$("#app").innerHTML=`<div class="auth-wrap"><div class="auth-card card"><h1>Simple Social couldn't start</h1><div class="notice">${esc(e.message)}</div><p class="muted">Check the Render environment variables and Firebase setup.</p></div></div>`});
