import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {createUserWithEmailAndPassword,onAuthStateChanged,signInWithEmailAndPassword,signOut,updateProfile} from "firebase/auth";
import {addDoc,collection,deleteDoc,doc,getDoc,getDocs,increment,limit,orderBy,query,serverTimestamp,setDoc,where} from "firebase/firestore";
import {auth,db} from "./firebase";
import "./styles.css";

function App(){
 const [user,setUser]=useState(null),[profile,setProfile]=useState({username:"",displayName:"",bio:""}),[following,setFollowing]=useState([]),[view,setView]=useState("home"),[posts,setPosts]=useState([]),[loading,setLoading]=useState(true),[refresh,setRefresh]=useState(0);
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(u){await loadProfile(u.uid);await loadFollowing(u.uid)}else{setProfile(null);setFollowing([])}setLoading(false)}),[]);
 useEffect(()=>{if(user)loadPosts()},[user,following,refresh]);
 async function loadProfile(uid){const s=await getDoc(doc(db,"users",uid));if(s.exists()){setProfile({id:s.id,...s.data()});return}const fallback={username:(auth.currentUser?.email?.split("@")[0]||"user").toLowerCase().replace(/[^a-z0-9_]/g,""),displayName:auth.currentUser?.displayName||auth.currentUser?.email?.split("@")[0]||"User",bio:"",createdAt:serverTimestamp()};await setDoc(doc(db,"users",uid),fallback,{merge:true});setProfile({id:uid,...fallback})}
 async function loadFollowing(uid){const s=await getDocs(query(collection(db,"follows"),where("followerId","==",uid)));setFollowing(s.docs.map(x=>x.data().followingId))}
 async function loadPosts(){const s=await getDocs(query(collection(db,"posts"),orderBy("createdAt","desc"),limit(50)));setPosts(s.docs.map(x=>({id:x.id,...x.data()})))}
 async function createPost(text){if(!text.trim())return;await addDoc(collection(db,"posts"),{authorId:user.uid,authorName:profile.displayName||profile.username,text:text.trim(),likeCount:0,commentCount:0,createdAt:serverTimestamp()});setRefresh(x=>x+1)}
 async function toggleLike(post){const ref=doc(db,"likes",`${post.id}_${user.uid}`),s=await getDoc(ref);if(s.exists()){await deleteDoc(ref);await setDoc(doc(db,"posts",post.id),{likeCount:increment(-1)},{merge:true})}else{await setDoc(ref,{postId:post.id,userId:user.uid,createdAt:serverTimestamp()});await setDoc(doc(db,"posts",post.id),{likeCount:increment(1)},{merge:true})}setRefresh(x=>x+1)}
 async function addComment(postId,text){if(!text.trim())return;await addDoc(collection(db,"comments"),{postId,authorId:user.uid,authorName:profile.displayName||profile.username,text:text.trim(),createdAt:serverTimestamp()});await setDoc(doc(db,"posts",postId),{commentCount:increment(1)},{merge:true});setRefresh(x=>x+1)}
 async function deletePost(id){if(!confirm("Delete this post?"))return;await deleteDoc(doc(db,"posts",id));const cs=await getDocs(query(collection(db,"comments"),where("postId","==",id)));for(const c of cs.docs)await deleteDoc(c.ref);const ls=await getDocs(query(collection(db,"likes"),where("postId","==",id)));for(const l of ls.docs)await deleteDoc(l.ref);setRefresh(x=>x+1)}
 async function follow(uid){if(!user||uid===user.uid)return;await setDoc(doc(db,"follows",`${user.uid}_${uid}`),{followerId:user.uid,followingId:uid,createdAt:serverTimestamp()});await loadFollowing(user.uid)}
 async function unfollow(uid){await deleteDoc(doc(db,"follows",`${user.uid}_${uid}`));await loadFollowing(user.uid)}
 if(loading)return <div className="center">Loading…</div>; if(!user)return <Auth/>;
 const feed=posts.filter(p=>p.authorId===user.uid||following.includes(p.authorId));
 return <><header><button className="brand" onClick={()=>setView("home")}>Simple Social</button><nav><button onClick={()=>setView("home")}>Home</button><button onClick={()=>setView("search")}>Search</button><button onClick={()=>setView("profile")}>Profile</button><button className="logout" onClick={()=>signOut(auth)}>Log out</button></nav></header><main className="container">
 {view==="home"&&<><Composer onPost={createPost}/><div className="section-title"><h2>Your feed</h2><button onClick={()=>setRefresh(x=>x+1)}>Refresh</button></div>{feed.length?feed.map(p=><Post key={p.id} post={p} user={user} onLike={()=>toggleLike(p)} onComment={addComment} onDelete={()=>deletePost(p.id)}/>):<div className="card empty">No posts yet. Follow someone or make your first post.</div>}</>}
 {view==="profile"&&<Profile user={user} profile={profile} posts={posts.filter(p=>p.authorId===user.uid)} onSave={async data=>{await setDoc(doc(db,"users",user.uid),data,{merge:true});await updateProfile(user,{displayName:data.displayName});setProfile({...profile,...data});setRefresh(x=>x+1)}} onLike={toggleLike} onComment={addComment} onDelete={deletePost}/>} 
 {view==="search"&&<Search user={user} following={following} onFollow={follow} onUnfollow={unfollow}/>} 
 </main></>
}

function Auth(){const[mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[username,setUsername]=useState(""),[error,setError]=useState("");async function submit(e){e.preventDefault();setError("");try{if(mode==="signup"){const c=await createUserWithEmailAndPassword(auth,email,password);const clean=username.toLowerCase().replace(/[^a-z0-9_]/g,"");await updateProfile(c.user,{displayName:username});await setDoc(doc(db,"users",c.user.uid),{username:clean,displayName:username,bio:"",createdAt:serverTimestamp()})}else await signInWithEmailAndPassword(auth,email,password)}catch(e){setError(e.message.replace("Firebase: ",""))}}return <div className="auth"><div className="card auth-card"><h1>Simple Social</h1><p className="muted">{mode==="login"?"Welcome back.":"Create an account."}</p><form onSubmit={submit}>{mode==="signup"&&<input placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} required/>}<input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} minLength="6" required/>{error&&<p className="error">{error}</p>}<button className="primary">{mode==="login"?"Log in":"Sign up"}</button></form><button className="link" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Need an account? Sign up":"Already have an account? Log in"}</button></div></div>}

function Composer({onPost}){const[t,setT]=useState("");return <form className="card composer" onSubmit={async e=>{e.preventDefault();await onPost(t);setT("")}}><textarea value={t} maxLength="500" placeholder="What's on your mind?" onChange={e=>setT(e.target.value)}/><div className="row"><span className="muted">{t.length}/500</span><button className="primary" disabled={!t.trim()}>Post</button></div></form>}

function Post({post,user,onLike,onComment,onDelete}){const[liked,setLiked]=useState(false),[comments,setComments]=useState([]),[open,setOpen]=useState(false),[text,setText]=useState("");useEffect(()=>{getDoc(doc(db,"likes",`${post.id}_${user.uid}`)).then(s=>setLiked(s.exists()))},[post.id,user.uid]);async function toggle(){await onLike();setLiked(v=>!v)}async function loadComments(){const s=await getDocs(query(collection(db,"comments"),where("postId","==",post.id)));const data=s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0));setComments(data);setOpen(v=>!v)}async function submit(e){e.preventDefault();if(!text.trim())return;await onComment(post.id,text);setText("");const s=await getDocs(query(collection(db,"comments"),where("postId","==",post.id)));setComments(s.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0)));setOpen(true)}return <article className="card post"><div className="post-head"><strong>{post.authorName||"User"}</strong><span className="muted">{post.createdAt?.toDate?.().toLocaleString()||"just now"}</span></div><p className="post-text">{post.text}</p><div className="actions"><button className={liked?"liked":""} onClick={toggle}>{liked?"♥":"♡"} {post.likeCount||0}</button><button onClick={loadComments}>💬 {post.commentCount||0}</button>{post.authorId===user.uid&&<button className="danger" onClick={onDelete}>Delete</button>}</div>{open&&<div className="comments">{comments.length?comments.map(c=><div className="comment" key={c.id}><strong>{c.authorName}</strong><span>{c.text}</span></div>):<p className="muted">No comments yet.</p>}<form className="comment-form" onSubmit={submit}><input placeholder="Write a comment…" value={text} onChange={e=>setText(e.target.value)}/><button disabled={!text.trim()}>Send</button></form></div>}</article>}

function Profile({user,profile,posts,onSave,onLike,onComment,onDelete}){const[editing,setEditing]=useState(false),[displayName,setDisplayName]=useState(profile.displayName||""),[username,setUsername]=useState(profile.username||""),[bio,setBio]=useState(profile.bio||"");return <section><div className="card profile"><div className="avatar">{(displayName||"U")[0].toUpperCase()}</div><h1>{displayName||"User"}</h1><p className="muted">@{username}</p><p>{bio||"No bio yet."}</p><div className="stats"><b>{posts.length}</b> posts</div><button onClick={()=>setEditing(v=>!v)}>{editing?"Cancel":"Edit profile"}</button>{editing&&<form className="edit-form" onSubmit={async e=>{e.preventDefault();await onSave({displayName,username:username.toLowerCase().replace(/[^a-z0-9_]/g,""),bio});setEditing(false)}}><input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="Display name" required/><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Username" required/><textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength="160" placeholder="Bio"/><button className="primary">Save profile</button></form>}</div><h2>Your posts</h2>{posts.map(p=><Post key={p.id} post={p} user={user} onLike={()=>onLike(p)} onComment={onComment} onDelete={()=>onDelete(p.id)}/>)}</section>}

function Search({user,following,onFollow,onUnfollow}){const[t,setT]=useState(""),[results,setResults]=useState([]),[searched,setSearched]=useState(false);async function run(){const term=t.trim().toLowerCase();if(!term){setResults([]);return}const s=await getDocs(query(collection(db,"users"),where("username",">=",term),where("username","<=",term+"\uf8ff"),limit(20)));setResults(s.docs.map(x=>({id:x.id,...x.data()})));setSearched(true)}return <section><h1>Search</h1><div className="search"><input placeholder="Search usernames…" value={t} onChange={e=>setT(e.target.value)} onKeyDown={e=>e.key==="Enter"&&run()}/><button className="primary" onClick={run}>Search</button></div>{searched&&!results.length&&<div className="card empty">No users found.</div>}{results.map(p=><div className="card user" key={p.id}><div><strong>{p.displayName}</strong><span className="muted">@{p.username}</span></div>{p.id!==user.uid&&<button onClick={()=>following.includes(p.id)?onUnfollow(p.id):onFollow(p.id)}>{following.includes(p.id)?"Unfollow":"Follow"}</button>}</div>)}</section>}

createRoot(document.getElementById("root")).render(<App/>);
